# ======================================================================
# Config: spotify-player
# File: ~/.config/spotify-player/keymap.toml
# Platform: desktop
# Link: https://github.com/aome510/spotify-player
# ======================================================================

[[keymaps]]
command = "Quit"
key_sequence = "q"
  
[[keymaps]]
command = "PageSelectPreviousOrScrollUp"
key_sequence = "C-u"

[[keymaps]]
command = "PageSelectNextOrScrollDown"
key_sequence = "C-d"
