# ======================================================================
# Config: hyprpaper
# File: ~/.config/hypr/hyprlock.conf
# Platform: laptop
# Link: https://github.com/hyprwm/hyprpaper
# ======================================================================

splash = false

wallpaper {
		monitor = eDP-1
		path = ~/Vault/Wallpapers/1monitor/colorful.jpg
		fit_mode = cover
	}

wallpaper {
		monitor = HDMI-A-1
		path = ~/Vault/Wallpapers/1monitor/colorful.jpg
		fit_mode = cover
	}
