###########################################################################
#██╗░░██╗██╗░░░██╗██████╗░██████╗░██████╗░░█████╗░██████╗░███████╗██████╗░#
#██║░░██║╚██╗░██╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗#
#███████║░╚████╔╝░██████╔╝██████╔╝██████╔╝███████║██████╔╝█████╗░░██████╔╝#
#██╔══██║░░╚██╔╝░░██╔═══╝░██╔══██╗██╔═══╝░██╔══██║██╔═══╝░██╔══╝░░██╔══██╗#
#██║░░██║░░░██║░░░██║░░░░░██║░░██║██║░░░░░██║░░██║██║░░░░░███████╗██║░░██║#
#╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═╝░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚═╝░░░░░╚══════╝╚═╝░░╚═╝#
###########################################################################

splash = false

wallpaper {
		monitor = eDP-1
		path = ~/Vault/Wallpapers/1monitor/colorful.jpg
		fit_mode = cover
	}

wallpaper {
		monitor = HDMI-A-1
		path = ~/Vault/Wallpapers/1monitor/colorful.jpg
		fit_mode = cover
	}
