# ======================================================================
# Config: swayosd
# File: ~/.config/swayosd/config.toml
# Platform: desktop
# Link: https://github.com/ErikReider/SwayOSD
# ======================================================================

[server]
show_percentage = true
max_volume = 100
# style = "./style.css"
