# ======================================================================
# Config: hyprpaper
# File: ~/.config/hypr/hyprpaper.conf
# Platform: desktop
# Link: https://github.com/hyprwm/hyprpaper
# ======================================================================

splash = false

# Main Monitor
wallpaper {
		monitor = DP-1
		path = ~/Vault/Wallpapers/2monitors/split/burst-l.png
		fit_mode = cover
	}

# Side Monitor
wallpaper {
		monitor = HDMI-A-1
		path = ~/Vault/Wallpapers/2monitors/split/burst-r.png
		fit_mode = cover
	}
