# ======================================================================
# Config: hypridle
# File: ~/.config/hypr/hypridle.conf
# Platform: desktop
# Link: https://github.com/hyprwm/hypridle
# ======================================================================

general {
    ignore_dbus_inhibit = false               # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false            # whether to ignore systemd-inhibit --what=idle inhibitors
}

listener {
  timeout = 1170
  on-timeout = notify-send -t 2000 -h int:transient:1 "Sleep 30 seconds..."
}

listener {
  timeout = 1200
  on-timeout = systemctl suspend              # command to run when timeout has passed
}
