# ======================================================================
# Config: Hyprpaper
# File: hyprpaper.conf
# Platform: archbox
# ======================================================================

splash = false

# Main Monitor
wallpaper {
		monitor = DP-1
		path = ~/Vault/Wallpapers/2monitors/split/burst-l.png
		fit_mode = cover
	}

# Side Monitor
wallpaper {
		monitor = HDMI-A-1
		path = ~/Vault/Wallpapers/2monitors/split/burst-r.png
		fit_mode = cover
	}
