return {
	'btj93/fireworks.nvim',
	event = 'VeryLazy',
	opts = {},
	config = function()
		require('fireworks').setup({
			events = { 'BufWritePost' },
			launch_chance = 1.0,
			rockets = { min = 2, max = 5 },
			stagger = { first = { 0.3, 0.8 }, between = { 0.4, 1.4 } },
			tail_tint = 1.0,
			types = {
				peony = 4,
				chrysanthemum = 3,
				willow = 2,
				ring = 2,
				crossette = 2,
				crackle = 2,
				pistil = 2,
				palm = 2,
				kamuro = 1,
				salute = 1,
			},
			palettes = {
				single = 4,
				two_tone = 3,
				rainbow = 2,
				gold = 2,
			},
			sizes = {
				small = 3,
				medium = 4,
				large = 2,
			},
			colors = { '#7aa2f7', '#449dab', '#9ece6a', '#ad8ee6', '#f7768e', '#787c99', '#e0af68' },
			gold = { '#ffd700', '#ffb347', '#fff1a8' },
			fail_chance = 0.05,
			fps = 30,
			max_particles = 400,
			light = {
				radius = 25,
				brightness = 0.7,
				attack_ms = 80,
				duration_ms = 900,
				bg = 0.25,
				fg = 1.0,
				glow = 0.35,
				glow_radius = 6,
			},
			burn = {
				duration_ms = 2000,
				color = '#6b5d4f',
				smoke = true,
			},
			ignore_filetypes = {
				'TelescopePrompt',
				'TelescopeResults',
				'NvimTree',
				'neo-tree',
				'lazy',
				'mason',
				'help',
				'dashboard',
				'alpha',
				'starter',
				'notify',
				'noice',
				'trouble',
				'qf',
				'fugitive',
				'gitcommit',
			},
		})
	end,
}
